---
title: "ExploratoryDataAnalysisCourseProject1"
author: "Chia-Hsun Cheng"
date: "5/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE) # Set cache
```

## Download, Read and Process Data

```{r}
# download.file('https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip', './household_power_consumption.zip')
```

```{r}
library(readr)
powerConsumption <- read_delim('./household_power_consumption.zip', delim=';')
head(powerConsumption)
```

```{r}
library(dplyr)
usedPowerConsumption <- filter(powerConsumption, Date == '1/2/2007' |  Date == '2/2/2007')
```

```{r}
library(lubridate)
usedPowerConsumption <- mutate(usedPowerConsumption, datetime = dmy_hms((paste(Date, Time))))
head(select(usedPowerConsumption, Date, Time, datetime))
```

* We create a new field `datetime` to store the calculation of `Date` and `Time` for easier query.

## Plot 1

```{r}
hist(usedPowerConsumption$Global_active_power, xlab="Global Active Power (kilowatts)", main="Global Active Power", col="red")
```

## Plot2

```{r}
Sys.setlocale(category = "LC_ALL", locale = "en_US.UTF-8")
with(usedPowerConsumption, plot(datetime, Global_active_power, type="l", ylab = "Global Active Power (kilowatts)", xlab=""))
```

## Plot3

```{r}
Sys.setlocale(category = "LC_ALL", locale = "en_US.UTF-8")
with(usedPowerConsumption, plot(datetime, Sub_metering_1, type="n", ylab="Energy sub metering", xlab=""))
with(usedPowerConsumption, lines(datetime, Sub_metering_1))
with(usedPowerConsumption, lines(datetime, Sub_metering_2, col="red"))
with(usedPowerConsumption, lines(datetime, Sub_metering_3, col="blue"))
legend("topright", bty="n", lty = c(1, 1, 1), col=c("black","red","blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
```

## Plot4

```{r}
Sys.setlocale(category = "LC_ALL", locale = "en_US.UTF-8")
par(mfrow = c(2, 2))

# 1
with(usedPowerConsumption, plot(datetime, Global_active_power, type="l", ylab = "Global Active Power", xlab=""))
# 2
with(usedPowerConsumption, plot(datetime, Voltage, type="l", ylab = "Voltage"))
# 3
with(usedPowerConsumption, plot(datetime, Sub_metering_1, type="n", ylab="Energy sub metering", xlab=""))
with(usedPowerConsumption, lines(datetime, Sub_metering_1))
with(usedPowerConsumption, lines(datetime, Sub_metering_2, col="red"))
with(usedPowerConsumption, lines(datetime, Sub_metering_3, col="blue"))
legend("topright", bty="n", lty = c(1, 1, 1), col=c("black","red","blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
# 4
with(usedPowerConsumption, plot(datetime, Global_reactive_power, type="l"))
```
